### ISSUE TITLE
总是报错aiohttp.client_exceptions.ServerDisconnectedError: None

### ISSUE THREAD

**Issue by swifteen** [soulteary/docker-gitbook-pdf-generator#12]
Traceback (most recent call last):
  File "/app/gitbook.py", line 303, in <module>
    Gitbook2PDF(url).run()
  File "/app/gitbook.py", line 192, in run
    loop.run_until_complete(self.crawl_main_content(content_urls))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/app/gitbook.py", line 214, in crawl_main_content
    await asyncio.gather(*tasks)
  File "/app/gitbook.py", line 233, in gettext
    metatext = await request(url, self.headers)
  File "/app/gitbook.py", line 16, in request
    async with session.get(url, headers=headers, timeout=timeout) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 844, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 588, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None

**Comment by soulteary** [comment]
https://stackoverflow.com/questions/55853195/getting-serverdisconnectederror-exceptions-would-connection-release-help-fix
