### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lesterpang** [soulteary/docker-gitbook-pdf-generator#2]
```
/Users/xxx/Downloads$ docker run --rm -v `pwd`/fonts:/app/fonts \
                -v `pwd`/output:/app/output \
                soulteary/docker-gitbook-pdf-generator "http://self-publishing.ebookchain.org"
/usr/local/lib/python3.7/site-packages/weasyprint/fonts.py:230: UserWarning: FontConfig: No fonts configured. Expect ugly output.
  'FontConfig: No fonts configured. '
crawling :  http://self-publishing.ebookchain.org/index.html
crawling :  http://self-publishing.ebookchain.org/1-干嘛要写书？/1-写书的必要性/readme.html
crawling :  http://self-publishing.ebookchain.org/1-干嘛要写书？/2-写书的好处/readme.html
crawling :  http://self-publishing.ebookchain.org/2-什么是自出版平台？/readme.html
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/readme.html
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/1-Summary的安装.html
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/2-Summary的使用.html
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/3-电子书的生成.html
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/4-电子书的发布.html
crawling :  http://self-publishing.ebookchain.org/4-最佳实践/妙手偶得无须刻意.html
crawling :  http://self-publishing.ebookchain.org/5-附录/0-参考信息.html
crawling :  http://self-publishing.ebookchain.org/5-附录/1-关于作者.html
done :  http://self-publishing.ebookchain.org/1-干嘛要写书？/2-写书的好处/readme.html
done :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/1-Summary的安装.html
done :  http://self-publishing.ebookchain.org/1-干嘛要写书？/1-写书的必要性/readme.html
done :  http://self-publishing.ebookchain.org/2-什么是自出版平台？/readme.html
done :  http://self-publishing.ebookchain.org/4-最佳实践/妙手偶得无须刻意.html
done :  http://self-publishing.ebookchain.org/5-附录/0-参考信息.html
done :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/2-Summary的使用.html
retrying :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/readme.html
retrying :  http://self-publishing.ebookchain.org/index.html
retrying :  http://self-publishing.ebookchain.org/5-附录/1-关于作者.html
retrying :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/4-电子书的发布.html
retrying :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/3-电子书的生成.html
done :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/4-电子书的发布.html
done :  http://self-publishing.ebookchain.org/index.html
done :  http://self-publishing.ebookchain.org/5-附录/1-关于作者.html
Traceback (most recent call last):
  File "/app/gitbook.py", line 303, in <module>
    Gitbook2PDF(url).run()
  File "/app/gitbook.py", line 192, in run
    loop.run_until_complete(self.crawl_main_content(content_urls))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/app/gitbook.py", line 214, in crawl_main_content
    await asyncio.gather(*tasks)
  File "/app/gitbook.py", line 233, in gettext
    metatext = await request(url, self.headers)
  File "/app/gitbook.py", line 16, in request
    async with session.get(url, headers=headers, timeout=timeout) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 844, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 588, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
```

**Comment by soulteary** [comment]
仔细看文章 :)
